/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package RankingNazwisk;

import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author sterr
 */
public class OknoGlowne extends javax.swing.JFrame {

    String wybor;
    public Czytnik czytnik;

    /**
     * Creates new form OknoGlowne
     */
    public OknoGlowne() {
        initComponents();
        czytnik = new Czytnik();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextWpisz = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jRadioZenskie = new javax.swing.JRadioButton();
        jRadioMeskie = new javax.swing.JRadioButton();
        jRadioWszystkie = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonSzukaj = new javax.swing.JButton();
        jButtonZakoncz = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ranking imion na podstawie PESEL");

        jTextWpisz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextWpiszActionPerformed(evt);
            }
        });

        jLabel2.setText("Filtruj po nazwisku:");

        jLabel3.setText("Filtruj po p³ci:");

        jRadioZenskie.setText("¯eñskie");
        jRadioZenskie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioZenskieActionPerformed(evt);
            }
        });

        jRadioMeskie.setText("Mêskie");
        jRadioMeskie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioMeskieActionPerformed(evt);
            }
        });

        jRadioWszystkie.setText("Wszystkie");
        jRadioWszystkie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioWszystkieActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButtonSzukaj.setText("SZUKAJ");
        jButtonSzukaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSzukajActionPerformed(evt);
            }
        });

        jButtonZakoncz.setText("ZAKOÑCZ");
        jButtonZakoncz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZakonczActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jButtonZakoncz, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSzukaj, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextWpisz, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioZenskie)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioMeskie)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioWszystkie)))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextWpisz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioZenskie)
                        .addComponent(jRadioMeskie)
                        .addComponent(jRadioWszystkie)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSzukaj)
                    .addComponent(jButtonZakoncz))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextWpiszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextWpiszActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextWpiszActionPerformed

    //Dla wszystkich RadioButtonow sprawdzanie czy inne nie sa klikniete- jak sa to odznaczaja zeby byl tylko 1 klikniety
    private void jRadioZenskieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioZenskieActionPerformed
        // TODO add your handling code here:
        wybor = "zenskie";
        if (jRadioMeskie.isSelected()) {
            jRadioMeskie.setSelected(false);
        }
        jRadioWszystkie.setSelected(false);
    }//GEN-LAST:event_jRadioZenskieActionPerformed

    private void jRadioMeskieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioMeskieActionPerformed
        // TODO add your handling code here:
        wybor = "meskie";
        if (jRadioZenskie.isSelected()) {
            jRadioZenskie.setSelected(false);
        }
        jRadioWszystkie.setSelected(false);
    }//GEN-LAST:event_jRadioMeskieActionPerformed

    private void jRadioWszystkieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioWszystkieActionPerformed
        // TODO add your handling code here:
        wybor = "wszystkie";
        jRadioZenskie.setSelected(false);
        jRadioMeskie.setSelected(false);
    }//GEN-LAST:event_jRadioWszystkieActionPerformed

    private void jButtonSzukajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSzukajActionPerformed
        // TODO add your handling code here:
        //Jesli nie jest wybrane zadne Radio to wywala blad
        if (wybor == null) {
            JOptionPane.showMessageDialog(null, "Nie wybrano ¿adnych parametrów wyszukiwania",
                    "B³¹d!", JOptionPane.INFORMATION_MESSAGE);
        } else {
            List<String> wynik = null;
            String parametr;
            jTextArea1.setText("");
            //Sprawdzenie czy szukamy po naziwsku
            if (jTextWpisz.getText().isEmpty()) {
                parametr = "";
            } else {
                parametr = jTextWpisz.getText().toUpperCase();
            }
            //Sprawdzenie co wybral uzytkownik i wczytanie odpowiedniej listy
            if (wybor.contains("meskie")) {
                wynik = czytnik.CzytajMeskie(parametr);
            } else if (wybor.contains("zenskie")) {
                wynik = czytnik.CzytajDamskie(parametr);
            } else if (wybor.contains("wszystkie")) {
                wynik = czytnik.CzytajWszytskie(parametr);
            }
            if (wynik.isEmpty()){
            jTextArea1.setText("Nie znaleziono imienia "+ parametr + " w bazie.");
            }else {
            //Dodanie elementow z listy jeden po drugim do pola tekstowrgo
            for (int i = 0; i < wynik.size(); i++) {
                jTextArea1.append(wynik.get(i) + "\n");
            }
            }
        }
    }//GEN-LAST:event_jButtonSzukajActionPerformed

    private void jButtonZakonczActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZakonczActionPerformed
        // TODO add your handling code here:
        //Guzik zamykajacy program
        System.exit(0);
    }//GEN-LAST:event_jButtonZakonczActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OknoGlowne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OknoGlowne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OknoGlowne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OknoGlowne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OknoGlowne().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSzukaj;
    private javax.swing.JButton jButtonZakoncz;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioMeskie;
    private javax.swing.JRadioButton jRadioWszystkie;
    private javax.swing.JRadioButton jRadioZenskie;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextWpisz;
    // End of variables declaration//GEN-END:variables
}
